##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:
    # Useful URL: https://github.com/cafe-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-cafe-team/cafe-terminal
    - autoconf-archive
    - autopoint
    - clang
    - clang-tools
    - cppcheck
    - gcc
    - gettext
    - git
    - libdconf-dev
    - libglib2.0-dev
    - libsm-dev
    - libtool
    - libx11-dev
    - make
    - wget
    - yelp-tools

    #packages required for ctk
    - adwaita-icon-theme
    - dconf-gsettings-backend
    - hicolor-icon-theme
    - libatk-bridge2.0-dev
    - libatk-bridge2.0-0
    - libcolord2
    - libcups2
    - libegl1-mesa-dev
    - libepoxy0
    - libepoxy-dev
    - libfontconfig1-dev
    - libfribidi-dev
    - libgdk-pixbuf2.0-dev
    - libjson-glib-1.0-0
    - libpango1.0-dev
    - librest-0.7-0
    - libwayland-dev
    - libx11-dev
    - libxcomposite-dev
    - libxcursor-dev
    - libxdamage-dev
    - libxext-dev
    - libxfixes-dev
    - libxi-dev
    - libxinerama-dev
    - libxkbcommon-dev
    - libxrandr-dev
    - wayland-protocols

before_scripts:
  - export TITLECPPCHECK="${REPO_NAME} (cppcheck `dpkg -s cppcheck|grep -i version|cut -d " " -f 2`)"
  - cppcheck --xml --output-file=cppcheck.xml --enable=warning,style,performance,portability,information,missingInclude .
  - cppcheck-htmlreport --title="$TITLECPPCHECK" --file=cppcheck.xml --report-dir=cppcheck-htmlreport

  # Install cafe-common from master branch
  - cd ${START_DIR}
  - git clone --depth 1  https://github.com/cafe-desktop/cafe-common.git -b master cafe-common-master
  - cd cafe-common-master
  - ./autogen.sh
  - if [ ${DISTRO_NAME} == "debian" -o ${DISTRO_NAME} == "ubuntu" ];then
  -     ./configure --prefix=/usr --libdir=/usr/lib/x86_64-linux-gnu --libexecdir=/usr/lib/x86_64-linux-gnu
  - else
  -     ./configure --prefix=/usr
  - fi
  - make
  - make install
  - cd ..

  # Install required ctk .deb packages
  - wget https://github.com/cafe-desktop/ctk/releases/download/v`echo $CTK_MASTERV`/libctk-3-dev_`echo $CTK_MASTERV`-1_amd64.deb
  - wget https://github.com/cafe-desktop/ctk/releases/download/v`echo $CTK_MASTERV`/gir1.2-ctk-3.0_`echo $CTK_MASTERV`-1_amd64.deb
  - wget https://github.com/cafe-desktop/ctk/releases/download/v`echo $CTK_MASTERV`/libctk-3-common_`echo $CTK_MASTERV`-1_all.deb
  - wget https://github.com/cafe-desktop/ctk/releases/download/v`echo $CTK_MASTERV`/libctk-3-0_`echo $CTK_MASTERV`-1_amd64.deb
  - dpkg -i *.deb

  # Install required bte .deb packages
  - git clone --depth 1  https://github.com/cafe-desktop/bte.git -b master bte-master
  - cd bte-master
  - wget https://github.com/cafe-desktop/bte/releases/download/`git describe --abbrev=0 --tags`/libbte-2.91-dev_`git describe --abbrev=0 --tags|sed 's/^.//'`-1_amd64.deb
  - wget https://github.com/cafe-desktop/bte/releases/download/`git describe --abbrev=0 --tags`/gir1.2-bte-2.91_`git describe --abbrev=0 --tags|sed 's/^.//'`-1_amd64.deb
  - wget https://github.com/cafe-desktop/bte/releases/download/`git describe --abbrev=0 --tags`/libbte-2.91-common_`git describe --abbrev=0 --tags|sed 's/^.//'`-1_amd64.deb
  - wget https://github.com/cafe-desktop/bte/releases/download/`git describe --abbrev=0 --tags`/libbte-2.91-0_`git describe --abbrev=0 --tags|sed 's/^.//'`-1_amd64.deb
  - dpkg -i *.deb
  - cd ..

build_scripts:
  - export TITLESCANBUILD="${REPO_NAME} (clang-tools `dpkg -s clang-tools|grep -i version|cut -d " " -f 2`) - scan-build results"
  - mkdir html-report
  - cppcheck --enable=warning,style,performance,portability,information,missingInclude . 2>&1 | tee -a ./html-report/output_${TRAVIS_COMMIT}

  - NOCONFIGURE=1 ./autogen.sh
  - scan-build $CHECKERS ./configure --enable-compile-warnings=maximum
  - if [ $CPU_COUNT -gt 1 ]; then
  -     scan-build $CHECKERS --html-title="$TITLESCANBUILD" --keep-cc -o html-report make -j $CPU_COUNT 2>&1 | tee -a ./html-report/output_${TRAVIS_COMMIT}
  - else
  -     scan-build $CHECKERS --html-title="$TITLESCANBUILD" --keep-cc -o html-report make 2>&1 | tee -a ./html-report/output_${TRAVIS_COMMIT}
  - fi

  - make check 2>&1 | tee -a ./html-report/output_${TRAVIS_COMMIT}
  - echo Warnings detected in the logs `cat ./html-report/output_${TRAVIS_COMMIT} | grep -i warning | wc -l` 2>&1 | tee -a ./html-report/output_${TRAVIS_COMMIT}
  - make install

after_scripts:
  - make distcheck
  - if [ -f "gen-index" ]; then ./gen-index -l 20; fi

releases:
  draft: false
  prerelease: false
  checksum: true
  file_glob: true
  files: cafe-terminal-*.tar.xz
  github_release:
    tags: true
    overwrite: true
    base_version: 1.20.0
    notify_servers:
      - https://release.cafe-desktop.org/release
